NO_PENALTY = 'no_penalty'
HARD_CODED_PENALTY = 'hard_coded_penalty'
UNCERTAINTY_PENALTY = 'uncertainty_penalty'
POLICY_ENTROPY_PENALTY = 'policy_entropy_penalty'
MUNCHAUSEN_PENALTY = 'munchausen_penalty'